version: "3"
services:

  cad:
    image: ghcr.io/keeeal/openscad-build:latest
    volumes:
      - ./output/logs:/logs
      - ./output/parts:/parts
      - ./src/cad:/cad

  firmware:
    image: arduino-cli:latest
    build:
      context: .
      dockerfile: .docker/arduino-cli.Dockerfile
    volumes:
      - ./output/build:/build
      - ./src/firmware:/firmware

  format:
    image: ghcr.io/keeeal/openscad-format:latest
    volumes:
      - ./src/cad:/cad
      - ./src/firmware:/firmware

  dev:
    image: seacal-scanner-dev:latest
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    volumes:
      - ./output:/output
      - ./src/cad:/cad
      - ./src/firmware:/firmware
      - ./tests:/tests
