version: "3"
services:

  openscad:
    image: ghcr.io/keeeal/openscad-build:latest
    volumes:
      - ./output/logs:/logs
      - ./output/parts:/parts
      - ./src/cad:/cad

  arduino:
    image: seacal-scanner/arduino:latest
    build:
      context: .
      dockerfile: dockerfiles/arduino-cli.Dockerfile
    volumes:
      - ./output/build:/build
      - ./src/firmware:/firmware

  format:
    image: seacal-scanner/format:latest
    build:
      context: .
      dockerfile: dockerfiles/format.Dockerfile
    volumes:
      - ./src/cad:/cad
      - ./src/firmware:/firmware
      - ./tests:/tests

  test:
    image: seacal-scanner/test:latest
    build:
      context: .
      dockerfile: dockerfiles/test.Dockerfile
    volumes:
      - ./output:/output
      - ./src/cad:/cad
      - ./src/firmware:/firmware
      - ./tests:/tests
