version: "3"
services:

  cad:
    image: openscad/openscad:latest
    volumes:
      - ./src/cad:/cad
      - ./output/parts:/parts

  firmware:
    image: seacal-scanner-firmware:latest
    build:
      context: .
      dockerfile: .docker/firmware.Dockerfile
    volumes:
      - ./src/firmware:/firmware
      - ./output/build:/build

  format:
    image: seacal-scanner-format:latest
    build:
      context: .
      dockerfile: .docker/format.Dockerfile
    volumes:
      - ./src/cad:/cad
      - ./src/firmware:/firmware

  test:
    image: seacal-scanner-test:latest
    build:
      context: .
      dockerfile: .docker/test.Dockerfile
    volumes:
      - ./tests:/tests
      - ./src:/src
      - ./output:/output
