version: "3"
services:

  openscad:
    image: ghcr.io/keeeal/openscad-build:latest
    volumes:
      - ./output/logs:/logs
      - ./output/parts:/parts
      - ./src/cad:/cad

  arduino:
    image: arduino-cli:latest
    build:
      context: .
      dockerfile: dockerfiles/arduino-cli.Dockerfile
    volumes:
      - ./output/build:/build
      - ./src/firmware:/firmware

  format:
    image: seacal-scanner/format:latest
    volumes:
      - ./src/cad:/cad
      - ./src/firmware:/firmware

  dev:
    image: seacal-scanner/dev:latest
    build:
      context: .
      dockerfile: dockerfiles/dev.Dockerfile
    volumes:
      - ./output:/output
      - ./src/cad:/cad
      - ./src/firmware:/firmware
      - ./tests:/tests
