version: "3"
services:

  cad:
    image: openscad/openscad:latest
    volumes:
      - ./src/cad:/cad
      - ./output/parts:/parts
      - ./output/logs:/logs

  firmware:
    image: seacal-scanner:latest
    build:
      context: .
      dockerfile: .docker/firmware.Dockerfile
    volumes:
      - ./src/firmware:/firmware
      - ./output/build:/build

  format:
    image: seacal-scanner:latest
    build:
      context: .
      dockerfile: .docker/format.Dockerfile
    volumes:
      - ./src/cad:/cad
      - ./src/firmware:/firmware
