version: "3"
services:

  openscad:
    image: ghcr.io/keeeal/openscad-build:latest
    working_dir: /home
    volumes:
      - .:/home

  arduino:
    image: seacal-scanner/arduino:latest
    build:
      context: .
      dockerfile: dockerfiles/arduino-cli.Dockerfile
    working_dir: /home
    volumes:
      - .:/home

  kicad:
    image: kicad/kicad:8.0.0
    working_dir: /home
    volumes:
      - .:/home

  dev:
    image: seacal-scanner/dev:latest
    build:
      context: .
      dockerfile: dockerfiles/dev.Dockerfile
    working_dir: /home
    volumes:
      - .:/home
