version: "3"
services:

  cad:
    image: seacal-scanner-cad:latest
    build:
      context: .
      dockerfile: .docker/cad.Dockerfile
    volumes:
      - ./output/logs:/logs
      - ./output/parts:/parts
      - ./src/cad:/cad

  firmware:
    image: seacal-scanner-firmware:latest
    build:
      context: .
      dockerfile: .docker/firmware.Dockerfile
    volumes:
      - ./output/build:/build
      - ./src/firmware:/firmware

  format:
    image: seacal-scanner-format:latest
    build:
      context: .
      dockerfile: .docker/format.Dockerfile
    volumes:
      - ./src/cad:/cad
      - ./src/firmware:/firmware
      - ./tests:/tests

  test:
    image: seacal-scanner-test:latest
    build:
      context: .
      dockerfile: .docker/test.Dockerfile
    volumes:
      - ./output:/output
      - ./src:/src
      - ./tests:/tests
