name: CAD

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - src/cad/**/*
      - .github/workflows/cad.yaml

jobs:
  format-cad:
    name: Format CAD
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build docker image
      run: |
        make build service=format

    - name: Check formatting
      run: |
        make format-cad check=true

  build-cad:
    name: Build CAD
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build parts
      env:
        RENDER_QUALITY: 32
      run: |
        make cad

    - name: Archive parts
      uses: actions/upload-artifact@v3
      with:
        name: all-parts
        if-no-files-found: error
        path: |
          output/parts/*.stl
