name: CAD

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/cad.yaml
      - docker-compose.yaml
      - Makefile
      - src/cad/**/*

jobs:
  render-parts:
    name: Render parts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build docker images
      run: |
        docker compose build openscad
        docker compose build dev

    - name: Render parts
      run: |
        make render render-quality=16

    - name: Archive parts
      uses: actions/upload-artifact@v4
      with:
        name: parts
        if-no-files-found: error
        path: |
          build/parts/*.stl
          build/parts/*.log

    - name: Run tests
      run: |
        make test-cad
