name: CAD

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/cad.yaml
      - src/cad/**/*

jobs:
  build-parts:
    name: Build parts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build parts
      env:
        RENDER_QUALITY: 32
      run: |
        make parts

    - name: Archive parts
      uses: actions/upload-artifact@v3
      with:
        name: parts
        if-no-files-found: error
        path: |
          output/parts/*.stl
