name: CAD

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/cad.yaml
      - docker-compose.yaml
      - Makefile
      - src/cad/**/*

jobs:
  build-parts:
    name: Build parts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build docker images
      run: |
        docker compose build openscad
        docker compose build dev

    - name: Render parts
      run: |
        make render render-quality=32

    - name: Archive parts
      uses: actions/upload-artifact@v3
      with:
        name: parts
        if-no-files-found: error
        path: |
          output/parts/*.stl
          output/parts/*.log

    - name: Run tests
      run: |
        make test-cad
