name: Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-firmware:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile sketch
      uses: arduino/compile-sketches@v1
      with:
        fqbn: arduino:avr:leonardo
        sketch-paths: src/firmware

        # The cli-compile-flags needs to be a string that looks like a list but
        # isn't one and also requires an absolute path due to peculiarities of
        # the arduino/compile-sketches action...
        cli-compile-flags: |
          - --build-path=/home/runner/work/seacal-scanner/seacal-scanner/output/firmware

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        if-no-files-found: error
        path: |
          output/firmware/*.hex
