name: Firmware

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/firmware.yaml
      - docker-compose.yaml
      - Makefile
      - src/firmware/**/*

jobs:
  build-firmware:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build docker images
      run: |
        docker compose build firmware

    - name: Build firmware
      run: |
        make firmware

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        if-no-files-found: error
        path: |
          output/build/*.hex
