name: Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-firmware:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile sketch
      uses: arduino/compile-sketches@v1
      with:
        fqbn: arduino:avr:leonardo
        sketch-paths: src/firmware
        cli-compile-flags: |
          - --build-path=${GITHUB_WORKSPACE}/output/firmware

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        if-no-files-found: error
        path: |
          output/firmware/*.hex
