name: firmware

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/firmware.yaml
    - src/firmware/**/*
    - tests/firmware/**/*
    - Makefile

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Check formatting
      run: make format-firmware check=true

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: echo "$PWD/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: make arduino-cli
    - name: Build firmware
      run: make firmware
    - name: Archive firmware
      uses: actions/upload-artifact@v7
      with:
        name: firmware
        if-no-files-found: error
        path: build/firmware.ino.*
    - name: Run tests
      run: make test-firmware
