name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build docker images
      run: |
        docker compose build dev

    - name: Check formatting
      run: |
        make format check=true
