name: Format

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/format.yaml
      - src/cad/**/*
      - src/firmware/**/*

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build docker images
      run: |
        docker compose build format

    - name: Check formatting
      run: |
        make format check=true
