name: Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build docker image
      run: |
        make build service=format

    - name: Check formatting
      run: |
        make format check=true
