name: pcb

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - .github/workflows/pcb.yaml
    - src/pcb/**/*
    - tests/pcb/**/*
    - Makefile

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:kicad/kicad-10.0-releases
        sudo apt update
        sudo apt install kicad
    - name: Plot PCBs
      run: make pcb
    - uses: actions/upload-artifact@v7
      with:
        name: gerbers
        if-no-files-found: error
        path: gerbers/*/*
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: make test-pcb
